# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /migrations

pool:
  vmImage: ubuntu-latest

variables:
 group: DATA

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8.x'
 
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
     echo 'Starting bash task'
     python --version
     echo 'step1:Installing schemachange' 
     pip install schemachange
     echo 'Step 2: Running schemachange'
     schemachange -f migrations -a fd77989.central-india.azure -u JASHUVA -r ACCOUNTADMIN -w COMPUTE -d final -c final.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
  env: 
    SNOWFLAKE_PASSWORD: Jashuva9169@
     